# ai_tool.py

import pyautogui
import time
import subprocess
import os
import requests
from git import Repo
from transformers import pipeline

class AITool:
    def __init__(self):
        self.nlp_model = pipeline('text-classification', model='distilbert-base-uncased-finetuned-sst-2-english')

    def understand_command(self, command):
        return self.nlp_model(command)

    def execute_task(self, task_description):
        if 'open Canva' in task_description:
            self.open_canva()
        elif 'write code' in task_description:
            self.write_code(task_description)
        elif 'pull repo' in task_description:
            self.pull_repo(task_description)
        elif 'build n8n pipeline' in task_description:
            self.build_n8n_pipeline(task_description)
        else:
            print("Task not recognized.")

    def open_canva(self):
        subprocess.run(['open', '-a', 'Google Chrome', 'https://www.canva.com'])
        time.sleep(5)  # Wait for the page to load
        pyautogui.typewrite('your-email@example.com')
        pyautogui.press('tab')
        pyautogui.typewrite('your-password')
        pyautogui.press('enter')

    def write_code(self, task_description):
        # Use an LLM to generate code based on the task description
        code = self.generate_code(task_description)
        with open('generated_code.py', 'w') as file:
            file.write(code)
        print("Code written to generated_code.py")

    def generate_code(self, task_description):
        # Placeholder for LLM code generation
        return f"# Generated code for: {task_description}\nprint('Code generated by LLM')"

    def pull_repo(self, task_description):
        repo_url = self.extract_repo_url(task_description)
        repo_dir = self.extract_repo_dir(task_description)
        if not repo_dir:
            repo_dir = os.path.basename(repo_url).replace('.git', '')
        Repo.clone_from(repo_url, repo_dir)
        print(f"Repository cloned to {repo_dir}")

    def extract_repo_url(self, task_description):
        # Extract repo URL from task description
        # This is a simple example; you can improve it with regex or NLP
        if 'github.com/' in task_description:
            start = task_description.find('github.com/') + len('github.com/')
            end = task_description.find(' ', start)
            if end == -1:
                end = None
            return task_description[start:end]
        return None

    def extract_repo_dir(self, task_description):
        # Extract repo directory from task description
        # This is a simple example; you can improve it with regex or NLP
        if 'into ' in task_description:
            start = task_description.find('into ') + len('into ')
            end = task_description.find(' ', start)
            if end == -1:
                end = None
            return task_description[start:end]
        return None

    def build_n8n_pipeline(self, task_description):
        pipeline_name = self.extract_pipeline_name(task_description)
        pipeline_json = self.generate_n8n_pipeline(pipeline_name)
        with open(f'{pipeline_name}.json', 'w') as file:
            file.write(pipeline_json)
        print(f"n8n pipeline JSON written to {pipeline_name}.json")

    def extract_pipeline_name(self, task_description):
        # Extract pipeline name from task description
        # This is a simple example; you can improve it with regex or NLP
        if 'named ' in task_description:
            start = task_description.find('named ') + len('named ')
            end = task_description.find(' ', start)
            if end == -1:
                end = None
            return task_description[start:end]
        return None

    def generate_n8n_pipeline(self, pipeline_name):
        # Placeholder for n8n pipeline generation
        return f"""
        {{
          "name": "{pipeline_name}",
          "nodes": [
            {{
              "parameters": {{
                "path": "{pipeline_name}-trigger",
                "options": {{
                  "responseData": "OK"
                }}
              }},
              "id": "Webhook_1",
              "name": "Webhook",
              "type": "n8n-nodes-base.webhook",
              "typeVersion": 1,
              "position": [300, 300],
              "webhookId": "{pipeline_name}-trigger"
            }}
          ],
          "connections": {{
            "Webhook": {{
              "main": [
                [
                  {{
                    "node": "HTTP_1",
                    "type": "main",
                    "index": 0
                  }}
                ]
              ]
            }}
          }},
          "settings": {{}},
          "staticData": {{}},
          "meta": {{
            "template": true
          }}
        }}
        """

    def run(self):
        while True:
            command = input('Enter a command: ')
            interpretation = self.understand_command(command)
            self.execute_task(interpretation)

if __name__ == '__main__':
    ai_tool = AITool()
    ai_tool.run()